# YAML for launching the orderer
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: peer2-govaphospital
  labels:
    app: peer2-govaphospital
spec:
  serviceName: peer2-govaphospital
  replicas: 1
  selector:
    matchLabels:
      app: peer2-govaphospital
  template:
    metadata:
      labels:
        app: peer2-govaphospital
    spec:
      containers:
      - name: peer2-govaphospital
        # image used
        image: nhutori4/peer2-govaphospital:dev
        # Uncomment the following during development/testing of the image
        imagePullPolicy: Always
        env:
          - name: FABRIC_LOGGING_SPEC
            value: INFO
          - name: ORDERER_ADDRESS
            value: orderer1-ordererorg:30750
          - name: FABRIC_LOGGING_SPEC
            value: debug
          - name: CORE_PEER_TLS_ENABLED
            value: "true"
          - name: CORE_PEER_GOSSIP_ORGLEADER
            value: "false"
          - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
            value: peer2-govaphospital:31851
          - name: CORE_PEER_GOSSIP_SKIPHANDSHAKE
            value: "true"
          - name: CORE_PEER_GOSSIP_BOOTSTRAP
            value: peer1-govaphospital:30851
        volumeMounts:
        - name: peer2-govaphospital-ledger
          mountPath: /var/ledger
        - name: dockersock
          mountPath: /var/run/docker.sock
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
  volumeClaimTemplates:
  - metadata: 
      name: peer2-govaphospital-ledger
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: storageclass-govaphospital
      resources:
        requests:
          storage: 1Gi

---
# Expose the port 30851 as ClusterIP
apiVersion: v1
kind: Service
metadata:
  name: peer2-govaphospital

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: peer2-govaphospital

  ports:
    - name: peer2-govaphospital
      port: 31851
    - name: peer2-govaphospital-cc-clusterip
      port: 30852

  type: ClusterIP

---
# Expose the port 30851 as node port -  NEEDED if you
# are interested in connecting to the Pods from the Host
# machine - keep in mind you would need the IP for the node
# port service
apiVersion: v1
kind: Service
metadata:
  name: peer2-govaphospital-nodeport

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: peer2-govaphospital

  ports:
    - name: peer2-govaphospital-nodeport-851
      port: 31851
      nodePort: 31851
    - name: peer2-govaphospital-cc-nodeport-852
      port: 31852
      nodePort: 31852

  type: NodePort
